# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - librechat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_93a0821a4e4340e1b3b1f4a50663b949 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_da59748a78bb41a5b655cdd70be34150 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_93a0821a4e4340e1b3b1f4a50663b949 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'librechat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30916fafc6924647a510fab130cfd831 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_93a0821a4e4340e1b3b1f4a50663b949 }}/appsvc/staticsite:${{ github.sha }}'